### ISSUE TITLE
Localytics.autoIntegrate(this, key) causes RuntimeException on API < 14.

### ISSUE THREAD

**Issue by jmiumv** [localytics/android-samples#4]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NoClassDefFoundError: com.localytics.android.LocalyticsActivityLifecycleCallbacks
                                                     at com.localytics.android.LocalyticsManager.autoIntegrate(LocalyticsManager.java:74)
                                                     at com.localytics.android.Localytics.autoIntegrate(Localytics.java:185)
                                                     at com.iconology.comics.app.ComicsApp.onCreate(ComicsApp.java:133)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3272)
                                                     at android.app.ActivityThread.access$2200(ActivityThread.java:117)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:130)
                                                     at android.app.ActivityThread.main(ActivityThread.java:3683)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:507)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                     at dalvik.system.NativeStart.main(Native Method)
```

Our apps support minSDK = 10 and this caveat was not mentioned anywhere in the docs, please update code samples or create a new one, with minSDK = 10 instead of minSDK = 14.

**Comment by jmiumv** [comment]
* I found it subtly mentioned here, https://docs.localytics.com/dev/android.html#messaging-callbacks-android. 

* I will keep this issue open till you can make this an important note on your documentation/setup page.

**Comment by Mriegel** [comment]
@vijayvikramreddy Sorry to hear you had trouble with this.  Indeed version 4 of our SDK only supported a `minSDKVersion` of 14.  I have just submitted a pull request to our docs repo to display this prominently.
