### ISSUE TITLE
App Crash: BadParcelableException

### ISSUE THREAD

**Issue by gerrygu** [localytics/android-samples#7]
my lib version is 4.5.1,
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.localytics.android.InAppConfiguration
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Mriegel** [comment]
@gerrygu Are you seeing this within one of the samples? If it is within one of the samples, could you shed some light as to what you are doing when you see this error occur?

**Comment by gerrygu** [comment]
@Mriegel Not the sample codes,  this crash is reported on the Crashlytics. and this crash has happened more than 1600 on my project.

**Comment by Mriegel** [comment]
@gerrygu If it is not related to any of the samples, then can you report this error to our support team (support@localytics.com), and we would be happy to assist you further through that channel.

Once again, since this isn't related to any samples, I will be closing this issue.

**Comment by utkan** [comment]
any progress on this issue?
